#!/usr/bin/env sh

if [ "$#" -eq 1 ]; then
  hcc -S -x cl -Xclang \
    -I/opt/rocm/hcc2/lib/libdevice/gfx900/include \
    -include opencl-c.h \
    -cl-std=CL2.0 \
    -Dcl_clang_storage_class_specifiers \
    -Dcl_khr_fp64 \
    -target amdgcn-amd-amdhsa \
    -c "$1"
else
  echo "Usage: ./cl_asm <source.cl>"
  exit 1
fi
