[package]
name = "reki-wasm"
version = "0.1.0"
authors = ["timlathy"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
path = "lib.rs"

[dependencies]
reki = { path = "reki/" }
wasm-bindgen = "0.2.56"
js-sys = "0.3.33"
